language: scala

# Get latest install-jdk.sh script
before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

matrix:
  include:
    # Java 10 "Oracle JDK" (not yet provided by Travis CI)
    - env: JDK='Oracle JDK 10'
      install: . ./install-jdk.sh -F 10 -L BCL
    # Java 10 "OpenJDK"
    - env: JDK='OpenJDK 10' JACOCO='-PenableJaCoCo'
      install: . ./install-jdk.sh -F 10 -L GPL

    # Java 8  Openjdk/Orclejdk
    - env:
        jdk: oraclejdk8
    - env:
        jdk: openjdk8

    # Java 11 "Oracle JDK"
    - env: JDK='Oracle JDK 11'
      install: . ./install-jdk.sh -F 11 -L BCL
    # The following environments are known to fail
  allow_failures:
    - env: JDK='Oracle JDK 11'

scala:
  - $scala_version$
script:
  - "sbt clean compile test"
